using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace _08_StripPrj
{
    public static class StripNames
    {
        // Fields
        public const string ABOUT_ITC = "&About ITC";
        public const string ADD_TO_REFERENCE_IMAGE = "Add To Reference Image";
        public const string ADJUST_LEVEL_WINDOW = "Adjust Level Window";
        public const string ALL_IMAGE_DISPLAY_ITEMS = "All";
        public const string APPROVE_STATE = "Approve State";
        public const string APPROVED = "Unapproved";
        public const string ARM_PARAMETER_SETTING = "&Frame Parameter Setting";
        public const string AUTO_REGISTRATION_BY_BONY_MARKERS_CURVE = "Auto-Registration by Bony Markers/Curve";
        public const string AUTO_REGISTRATION_BY_GOLD_MARKERS = "Auto-Registration by Gold Markers";
        public const string AUTO_REGISTRATION_BY_RECTANGLE_ROI = "Auto-Registration by Rectangle ROI";
        public const string BACKUP_DATABASE = "&Backup Database";
        public const string BOUNDARY = "Boundary";
        public const string CALCULATE = "&Calculate";
        public const string CAPTURE_PARAMETER_SETTING = "&Capture Parameter Setting";
        public const string CENTER = "Center";
        public const string CHEST_ENHANCEMENT = "Chest Enhancement";
        public const string CONFIGURATION_MENU = "&Configuration";
        public const string CONTOUR = "Contour";
        public const string COORDINATE_INFO = "Coordinate Info";
        public const string CROSSLINE_WITH_RULE = "CrossLine With Rule";
        public const string DB_MENU = "&Database";
        public const string DEFAULT_CURSOR = "Default Cursor";
        public const string DELETE_CURRENT_IMAGE = "Delete Current Image";
        public const string DICOM_AUTO_IMPORT_SETTING = "DICOM &Auto Import Setting";
        public const string DICOM_IMPORT = "Import DICOM";
        public const string DICOM_RECEIVE_SETTING = "DICOM &Receive Setting";
        public const string DICOM_SEND_SETTING = "DICOM &Send Setting";
        public const string DISPLAY_MODE_ALTERNATE = "Display mode: Alternate Display";
        public const string DISPLAY_MODE_OVERLAY = "Display mode: Overlay";
        public const string DISPLAY_MODE_TILE = "Display mode: Tile";
        public const string DISPLAY_MODE_TRANSPARENT_WINDOW = "Display mode: TransparentWindow";
        public const string DISPLAY_ROI_IMAGE = "Display ROI Image";
        public const string DRAW_CURVE = "Draw Curve";
        public const string DRAW_POLYGONAL_LINE = "Draw Polygonal Line";
        public const string DRAW_WHEEL_LINE = "Draw Wheel Line";
        public const string EXIT = "&Exit";
        public const string EXPORT_DOSE_IMAGE = "Export Dose Image";
        public const string EXPORT_IMAGE = "Export Image";
        public const string FILE_MENU = "&File";
        public const string FUNCTION_MENU = "&Function";
        public const string GENERAL_ENHANCEMENT = "General Enhancement";
        public const string GENERATE_DRR = "Generate &DRR";
        public const string GRID = "Grid";
        public const string HEAD_ENHANCEMENT = "Head Enhancement";
        public const string HELP_MENU = "&Help";
        public const string HISTOGRAM = "Histogram";
        public const string IMAGE_CAPTURE = "Image &Capture";
        public const string IMAGE_DISPLAY = "Image Display";
        public const string IMAGE_VALUE = "Image Value";
        public const string IMAGES_MENU = "&Imgaes";
        public const string INPUT_SHIFT_MANUALLY = "Input shift manually";
        public const string IVS_IGRT = "IVS &IGRT";
        public const string JAW_APERTURE = @"Jaw\Aperture";
        public const string LA_SERVICE_CLOSE_PATIENT = "Close Patient";
        public const string LA_SERVICE_OPEN_PATIENT = "Open Patient";
        public const string LOGIN = "&Login";
        public const string LOGOUT = "Log&out";
        public const string MAGNIFIER = "Magnifier";
        public const string MANAGE_DATABASE = "Manage &Database";
        public const string MANAGE_PATIENT = "Manage &Patient";
        public const string MANAGE_USER = "Manage &User";
        public const string MARKER_CURVE = @"Marker\Curve";
        public const string MEASURE_ANGLE = "Measure Angle";
        public const string MEASURE_LENGTH = "Ruler";
        public const string MLC_APPROVE = "Approved";
        public const string MLC_EXPORT = "Export";
        public const string MLC_EXPORTISO = "ExportISO";
        public const string MLC_IMPORT = "Import";
        public const string MLC_LEAF_POSITION_DELETE = "Delete Logic Position";
        public const string MLC_LEAF_POSITION_INSERT = "Insert Logic Position";
        public const string MLC_UNAPPROVE = "Unapproved";
        public const string MLC_VIEW_RESET = "Reset";
        public const string MLC_VIEW_SHOW_LEAF_NAME = "Leaf Position Name";
        public const string MOVE_COUCH_SHIFT_BY_COUCH_KICK = "Move Couch Shift by Couch Kick";
        public const string MOVE_IMAGE = "Move Image";
        public const string NECK_ENHANCEMENT = "Neck Enhancement";
        public const string NOTEPAD = "&Notepad";
        public const string OPTION_SETTING = "&Option Setting";
        public const string ORIGINAL_SIZE = "Original Size";
        public const string PAINT = "&Paint";
        public const string PATIENT_SCHEDULE = "&Patient Schedule";
        public const string PELVIS_ENHANCEMENT = "Pelvis Enhancement";
        public const string PROGRESS_BAR = "Progress Bar";
        public const string REPORT = "Report";
        public const string REQUEST_APPROVE = "Request approve";
        public const string RESET_OFFSET = "Reset Offset";
        public const string RESET_SHIFT = "Reset shift";
        public const string RESTORE_DATABASE = "&Restore Database";
        public const string RV_CONTINUE_CAPTURE = "Continue";
        public const string RV_PAUSE_CAPTURE = "Pause";
        public const string RV_Select_Images = "Select Images";
        public const string RV_Select_Range = "Select Range File";
        public const string RV_START_CAPTURE = "Start";
        public const string RV_STOP_CAPTURE = "Stop";
        public const string SELECT_RECTANGLE_ROI = "Select Rectangle ROI";
        public const string SELECT_ROI = "Select ROI";
        public const string SET_BONY_MARKERS = "Set Bony Markers";
        public const string SET_GOLD_MARKERS = "Set Gold Markers";
        public const string SET_NOTE = "Set Note";
        public const string STATUS_TIPS = "Status Tips";
        public const string TABLET = "T&ablet";
        public const string TEXT = "Text";
        public const string THERA_LOCK_STATE = "Thera Lock State";
        public const string TIME = "Time";
        public const string TOOL_MENU = "&Tool";
        public const string TRIGGER_PARAMETER_SETTING = "&Trigger Parameter Setting";
        public const string UPDATE_DATABASE = "&Update Database";
        public const string USER = "User";
        public const string VIEW_MENU = "&View";
    }
}
